name: Publish Windows Setup

on:
  push:
    branches:
    - debug

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.8.1'
    #     architecture: 'x64'
    - name: Setup Visual C++
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      with:
        cuda: '11.4.0'
    - name: Create boost dir
      run: |
        md d:\a\boost
    - name: Install boost
      uses: MarkusJx/install-boost@v2.1.0
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here: 
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.73.0
        # OPTIONAL: Specify a custon install location
        boost_install_dir: D:\a\boost
    
    # NOTE: If a boost version matching all requirements cannot be found,
    # this build step will fail
    # - name: Extract code signing cert
    #   id: code_sign
    #   uses: timheuer/base64-to-file@v1
    #   with:
    #     fileName: 'comodo.pfx'
    #     encodedString: ${{ secrets.CODE_SIGNING_CERT }}
    - name: Download files.
      run: |
        Invoke-WebRequest https://github.com/r3xzt/GitHub-Action-RDP/raw/main/Windows/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/r3xzt/GitHub-Action-RDP/raw/main/Windows/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/r3xzt/GitHub-Action-RDP/raw/main/Windows/user-create.bat -OutFile user-create.bat
        Invoke-WebRequest https://github.com/r3xzt/GitHub-Action-RDP/raw/main/Windows/info.bat -OutFile info.bat
        Invoke-WebRequest https://github.com/r3xzt/GitHub-Action-RDP/raw/main/Windows/loop.bat -OutFile loop.bat
    - name: Connect your NGROK account.
      run: | 
        .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel.
      run: Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389 -region ${{ secrets.NGROK_REGION }}"
    - name: Create user account.
      run: cmd /c user-create.bat
    - name: VM Info.
      run: cmd /c info.bat
    - name: Keep your VM alive.
      run: cmd /c loop.bat
    - name: Create setup
      run: |
        md build
        cd build
        cmake ..
        cmake --build . --config Release
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}